name: facebook
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  json_serializable: ^6.5.3
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  build_runner: ^2.3.2
  shared_preferences: 2.0.15
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/action/
  #   - images/a_dot_ham.jpeg